//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gitle.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gitle.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activeer.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle toegevoegd.
        /// </summary>
        public static string AddedAll {
            get {
                return ResourceManager.GetString("AddedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string Address_City_Help {
            get {
                return ResourceManager.GetString("Address_City_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer.
        /// </summary>
        public static string Address_Housenumber {
            get {
                return ResourceManager.GetString("Address_Housenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alleen het nummer.
        /// </summary>
        public static string Address_Housenumber_Help {
            get {
                return ResourceManager.GetString("Address_Housenumber_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoeging.
        /// </summary>
        public static string Address_HousenumberExtension {
            get {
                return ResourceManager.GetString("Address_HousenumberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventueele toevoeging.
        /// </summary>
        public static string Address_HousenumberExtension_Help {
            get {
                return ResourceManager.GetString("Address_HousenumberExtension_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerking.
        /// </summary>
        public static string Address_Note {
            get {
                return ResourceManager.GetString("Address_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evt. Bijzonderheden bij het ophalen.
        /// </summary>
        public static string Address_Note_Help {
            get {
                return ResourceManager.GetString("Address_Note_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straat.
        /// </summary>
        public static string Address_Street {
            get {
                return ResourceManager.GetString("Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straatnaam.
        /// </summary>
        public static string Address_Street_Help {
            get {
                return ResourceManager.GetString("Address_Street_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Address_Zipcode {
            get {
                return ResourceManager.GetString("Address_Zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode formaat: &apos;1111 XX&apos;.
        /// </summary>
        public static string Address_Zipcode_Help {
            get {
                return ResourceManager.GetString("Address_Zipcode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitle.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiveer.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearchiveerd.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgepakt.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandelaar.
        /// </summary>
        public static string Assigned_To {
            get {
                return ResourceManager.GetString("Assigned_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandelaar.
        /// </summary>
        public static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to om.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen niet gelukt.
        /// </summary>
        public static string Authenticate_Failed {
            get {
                return ResourceManager.GetString("Authenticate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar overzicht.
        /// </summary>
        public static string BackToIndex {
            get {
                return ResourceManager.GetString("BackToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefactureerd.
        /// </summary>
        public static string Billed {
            get {
                return ResourceManager.GetString("Billed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboekt.
        /// </summary>
        public static string Booked {
            get {
                return ResourceManager.GetString("Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to door.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wijzig.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geopend.
        /// </summary>
        public static string ChangeState_Opened {
            get {
                return ResourceManager.GetString("ChangeState_Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heropend.
        /// </summary>
        public static string ChangeState_Reopened {
            get {
                return ResourceManager.GetString("ChangeState_Reopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wis zoekresultaten.
        /// </summary>
        public static string Clear_Search {
            get {
                return ResourceManager.GetString("Clear_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesloten.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesloten op.
        /// </summary>
        public static string ClosedOn {
            get {
                return ResourceManager.GetString("ClosedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe reactie.
        /// </summary>
        public static string Comment_New {
            get {
                return ResourceManager.GetString("Comment_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compleet.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgevoerd.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevat een label.
        /// </summary>
        public static string ContainsLabel {
            get {
                return ResourceManager.GetString("ContainsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevat labels.
        /// </summary>
        public static string ContainsLabels {
            get {
                return ResourceManager.GetString("ContainsLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevat niet labels.
        /// </summary>
        public static string ContainsNotLabels {
            get {
                return ResourceManager.GetString("ContainsNotLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt op.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klant.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actieve Klanten.
        /// </summary>
        public static string Customer_Active {
            get {
                return ResourceManager.GetString("Customer_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klant toevoegen.
        /// </summary>
        public static string Customer_Add {
            get {
                return ResourceManager.GetString("Customer_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereiding diner.
        /// </summary>
        public static string Customer_CanCookAlone {
            get {
                return ResourceManager.GetString("Customer_CanCookAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of de klant zelfstandig diner kan bereiden of hierbij ondersteuning nodig heeft.
        /// </summary>
        public static string Customer_CanCookAlone_Help {
            get {
                return ResourceManager.GetString("Customer_CanCookAlone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vervoer.
        /// </summary>
        public static string Customer_CanDriveAlone {
            get {
                return ResourceManager.GetString("Customer_CanDriveAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of de klant zelfstandig kan rijden of hierbij ondersteuning nodig heeft.
        /// </summary>
        public static string Customer_CanDriveAlone_Help {
            get {
                return ResourceManager.GetString("Customer_CanDriveAlone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boodschappen doen.
        /// </summary>
        public static string Customer_CanShopAlone {
            get {
                return ResourceManager.GetString("Customer_CanShopAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of de klant zelfstandig boodschappen kan doen of hierbij ondersteuning nodig heeft.
        /// </summary>
        public static string Customer_CanShopAlone_Help {
            get {
                return ResourceManager.GetString("Customer_CanShopAlone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afspraak maken.
        /// </summary>
        public static string Customer_Create_Match {
            get {
                return ResourceManager.GetString("Customer_Create_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorkeur dagen.
        /// </summary>
        public static string Customer_DayPreference {
            get {
                return ResourceManager.GetString("Customer_DayPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies de voorkeur dag(en) van de klant.
        /// </summary>
        public static string Customer_DayPreference_Help {
            get {
                return ResourceManager.GetString("Customer_DayPreference_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieetwensen.
        /// </summary>
        public static string Customer_DietaryRequirements {
            get {
                return ResourceManager.GetString("Customer_DietaryRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier de dieetwensen in. Bijv. vegetarisch, halal, zoutarm, e.d..
        /// </summary>
        public static string Customer_DietaryRequirements_Help {
            get {
                return ResourceManager.GetString("Customer_DietaryRequirements_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerk klant.
        /// </summary>
        public static string Customer_Edit {
            get {
                return ResourceManager.GetString("Customer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorkeur samenstelling groep.
        /// </summary>
        public static string Customer_GroupCompositionPreference {
            get {
                return ResourceManager.GetString("Customer_GroupCompositionPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies de voorkeur voor de samenstelling van de groep: 60+ of alle leeftijden.
        /// </summary>
        public static string Customer_GroupCompositionPreference_Help {
            get {
                return ResourceManager.GetString("Customer_GroupCompositionPreference_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegankelijkheid woning.
        /// </summary>
        public static string Customer_HomeAccessibility {
            get {
                return ResourceManager.GetString("Customer_HomeAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan voor welke mobiliteiten de woning geschikt is.
        /// </summary>
        public static string Customer_HomeAccessibility_Help {
            get {
                return ResourceManager.GetString("Customer_HomeAccessibility_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De woning is toegankelijk voor.
        /// </summary>
        public static string Customer_HomeAccessibility_Label {
            get {
                return ResourceManager.GetString("Customer_HomeAccessibility_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisbezoek.
        /// </summary>
        public static string Customer_HouseVisit {
            get {
                return ResourceManager.GetString("Customer_HouseVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of deze klant een huisbezoek wenst.
        /// </summary>
        public static string Customer_HouseVisit_Help {
            get {
                return ResourceManager.GetString("Customer_HouseVisit_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja, deze klant wenst een huisbezoek.
        /// </summary>
        public static string Customer_HouseVisit_Label {
            get {
                return ResourceManager.GetString("Customer_HouseVisit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum van huisbezoek.
        /// </summary>
        public static string Customer_HouseVisitDate {
            get {
                return ResourceManager.GetString("Customer_HouseVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan op welke datum deze klant een huisbezoek wenst.
        /// </summary>
        public static string Customer_HouseVisitDate_Help {
            get {
                return ResourceManager.GetString("Customer_HouseVisitDate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearchiveerde klanten.
        /// </summary>
        public static string Customer_InActive {
            get {
                return ResourceManager.GetString("Customer_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobiliteit.
        /// </summary>
        public static string Customer_Mobility {
            get {
                return ResourceManager.GetString("Customer_Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier eventuele mobiliteitsproblemen van de klant in. Bijv. rollator, inklapbare rolstoel, rolstoelgebonden e.d..
        /// </summary>
        public static string Customer_Mobility_Help {
            get {
                return ResourceManager.GetString("Customer_Mobility_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijvingsdatum.
        /// </summary>
        public static string Customer_RegisterDate {
            get {
                return ResourceManager.GetString("Customer_RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanneer is deze persoon ingeschreven is in het systeem..
        /// </summary>
        public static string Customer_RegisterDate_Help {
            get {
                return ResourceManager.GetString("Customer_RegisterDate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingeschreven door.
        /// </summary>
        public static string Customer_RegisteredBy {
            get {
                return ResourceManager.GetString("Customer_RegisteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De persoon die deze klant heeft ingeschreven.
        /// </summary>
        public static string Customer_RegisteredBy_Help {
            get {
                return ResourceManager.GetString("Customer_RegisteredBy_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijving.
        /// </summary>
        public static string Customer_Registration {
            get {
                return ResourceManager.GetString("Customer_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klantcontacten.
        /// </summary>
        public static string CustomerContacts {
            get {
                return ResourceManager.GetString("CustomerContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen klantcontacten bekend.
        /// </summary>
        public static string CustomerContacts_None {
            get {
                return ResourceManager.GetString("CustomerContacts_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klanten.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verwijderd.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestemmingen.
        /// </summary>
        public static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen developers gevonden.
        /// </summary>
        public static string Developers_None {
            get {
                return ResourceManager.GetString("Developers_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenten.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgevoerd.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerk.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadres.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schatting.
        /// </summary>
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schatting Publiek.
        /// </summary>
        public static string Estimate_Public {
            get {
                return ResourceManager.GetString("Estimate_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschatte prijs.
        /// </summary>
        public static string Estimated_Price {
            get {
                return ResourceManager.GetString("Estimated_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschatte tijd.
        /// </summary>
        public static string Estimated_Time {
            get {
                return ResourceManager.GetString("Estimated_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporteer.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw filter.
        /// </summary>
        public static string Filter_New {
            get {
                return ResourceManager.GetString("Filter_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijdag.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volledige naam.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groep.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewenst aantal leden.
        /// </summary>
        public static string Group_CompleteCount {
            get {
                return ResourceManager.GetString("Group_CompleteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groepsleden.
        /// </summary>
        public static string Group_Customers {
            get {
                return ResourceManager.GetString("Group_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze groep is compleet.
        /// </summary>
        public static string Group_Make_Complete {
            get {
                return ResourceManager.GetString("Group_Make_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer.
        /// </summary>
        public static string Group_Number {
            get {
                return ResourceManager.GetString("Group_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle leeftijden.
        /// </summary>
        public static string GroupCompositionPreference_AllAges {
            get {
                return ResourceManager.GetString("GroupCompositionPreference_AllAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60+.
        /// </summary>
        public static string GroupCompositionPreference_SixtyPlus {
            get {
                return ResourceManager.GetString("GroupCompositionPreference_SixtyPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groepen.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doorgegeven.
        /// </summary>
        public static string HandedOver {
            get {
                return ResourceManager.GetString("HandedOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uur.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelfstandig.
        /// </summary>
        public static string Independently {
            get {
                return ResourceManager.GetString("Independently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factuurnummer(s).
        /// </summary>
        public static string Invoice_Numbers {
            get {
                return ResourceManager.GetString("Invoice_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiveer taak.
        /// </summary>
        public static string Issue_Archive {
            get {
                return ResourceManager.GetString("Issue_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluit taak.
        /// </summary>
        public static string Issue_Close {
            get {
                return ResourceManager.GetString("Issue_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak uitgevoerd.
        /// </summary>
        public static string Issue_Completed {
            get {
                return ResourceManager.GetString("Issue_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak bewerken.
        /// </summary>
        public static string Issue_Edit {
            get {
                return ResourceManager.GetString("Issue_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak doorgeven.
        /// </summary>
        public static string Issue_Forward {
            get {
                return ResourceManager.GetString("Issue_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe taak.
        /// </summary>
        public static string Issue_New {
            get {
                return ResourceManager.GetString("Issue_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak on hold.
        /// </summary>
        public static string Issue_OnHold {
            get {
                return ResourceManager.GetString("Issue_OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak oppakken.
        /// </summary>
        public static string Issue_PickUp {
            get {
                return ResourceManager.GetString("Issue_PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heropen taak.
        /// </summary>
        public static string Issue_Reopen {
            get {
                return ResourceManager.GetString("Issue_Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak {1} is aangepast door {0}.
        /// </summary>
        public static string IssueAction_Change_EmailSubject {
            get {
                return ResourceManager.GetString("IssueAction_Change_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak is aangepast.
        /// </summary>
        public static string IssueAction_Change_Text {
            get {
                return ResourceManager.GetString("IssueAction_Change_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is gereageerd op taak {1} door {0}.
        /// </summary>
        public static string IssueAction_Comment_EmailSubject {
            get {
                return ResourceManager.GetString("IssueAction_Comment_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoed status verwijderd.
        /// </summary>
        public static string IssueAction_Delete_Urgent {
            get {
                return ResourceManager.GetString("IssueAction_Delete_Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak is doorgegeven.
        /// </summary>
        public static string IssueAction_HandOver_Text {
            get {
                return ResourceManager.GetString("IssueAction_HandOver_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak is opgepakt.
        /// </summary>
        public static string IssueAction_PickUp_Text {
            get {
                return ResourceManager.GetString("IssueAction_PickUp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verplaats taken.
        /// </summary>
        public static string Issues_Move {
            get {
                return ResourceManager.GetString("Issues_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opnieuw nummeren.
        /// </summary>
        public static string Issues_Renumber {
            get {
                return ResourceManager.GetString("Issues_Renumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geselecteerde taken.
        /// </summary>
        public static string Issues_Selected {
            get {
                return ResourceManager.GetString("Issues_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label toevoegen.
        /// </summary>
        public static string Label_Add {
            get {
                return ResourceManager.GetString("Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatst gewijzigd.
        /// </summary>
        public static string LastChanged {
            get {
                return ResourceManager.GetString("LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingelogd blijven.
        /// </summary>
        public static string Login_Persistent {
            get {
                return ResourceManager.GetString("Login_Persistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maandag.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maand.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een maand.
        /// </summary>
        public static string Month_Help {
            get {
                return ResourceManager.GetString("Month_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhr..
        /// </summary>
        public static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mw..
        /// </summary>
        public static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string Name_Firstname {
            get {
                return ResourceManager.GetString("Name_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string Name_Firstname_Help {
            get {
                return ResourceManager.GetString("Name_Firstname_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht.
        /// </summary>
        public static string Name_Gender {
            get {
                return ResourceManager.GetString("Name_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht.
        /// </summary>
        public static string Name_Gender_Help {
            get {
                return ResourceManager.GetString("Name_Gender_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorletters.
        /// </summary>
        public static string Name_Initials {
            get {
                return ResourceManager.GetString("Name_Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorletters.
        /// </summary>
        public static string Name_Initials_Help {
            get {
                return ResourceManager.GetString("Name_Initials_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        public static string Name_Lastname {
            get {
                return ResourceManager.GetString("Name_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam zonder tussenvoegsel.
        /// </summary>
        public static string Name_Lastname_Help {
            get {
                return ResourceManager.GetString("Name_Lastname_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussenvoegsel.
        /// </summary>
        public static string Name_Middlename {
            get {
                return ResourceManager.GetString("Name_Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussenvoegsel o.a. : &apos;van&apos; enz..
        /// </summary>
        public static string Name_Middlename_Help {
            get {
                return ResourceManager.GetString("Name_Middlename_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef een naam op.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondersteuning nodig.
        /// </summary>
        public static string NeedsSupport {
            get {
                return ResourceManager.GetString("NeedsSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nee.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen labels om te filteren.
        /// </summary>
        public static string NoLabelsToFilter {
            get {
                return ResourceManager.GetString("NoLabelsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet opgepakt.
        /// </summary>
        public static string NotAssigned {
            get {
                return ResourceManager.GetString("NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerking.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U ontvangt geen notificaties..
        /// </summary>
        public static string Notifications_NotSubscribed {
            get {
                return ResourceManager.GetString("Notifications_NotSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alleen van zelf aangemaakte tickets.
        /// </summary>
        public static string Notifications_OnlyOwnTickets {
            get {
                return ResourceManager.GetString("Notifications_OnlyOwnTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties ontvangen.
        /// </summary>
        public static string Notifications_Receive {
            get {
                return ResourceManager.GetString("Notifications_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U ontvangt notificaties..
        /// </summary>
        public static string Notifications_Subscribed {
            get {
                return ResourceManager.GetString("Notifications_Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hold.
        /// </summary>
        public static string OnHold {
            get {
                return ResourceManager.GetString("OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alleen huidige project.
        /// </summary>
        public static string OnlyCurrentProject {
            get {
                return ResourceManager.GetString("OnlyCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geopend op.
        /// </summary>
        public static string Openend_On {
            get {
                return ResourceManager.GetString("Openend_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze link is verlopen..
        /// </summary>
        public static string Password_Change_Error_Expired {
            get {
                return ResourceManager.GetString("Password_Change_Error_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De wachtwoorden komen niet overeen. Probeer opnieuw..
        /// </summary>
        public static string Password_Change_Error_Mismatch {
            get {
                return ResourceManager.GetString("Password_Change_Error_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een mail verstuurd indien het adres bij ons bekend is..
        /// </summary>
        public static string Password_Change_Sent {
            get {
                return ResourceManager.GetString("Password_Change_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw wachtwoord is met succes gewijzigd. U kunt hieronder inloggen met uw nieuwe wachtwoord..
        /// </summary>
        public static string Password_Change_Success {
            get {
                return ResourceManager.GetString("Password_Change_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Person_Address {
            get {
                return ResourceManager.GetString("Person_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschikbaarheid.
        /// </summary>
        public static string Person_Availability {
            get {
                return ResourceManager.GetString("Person_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschikbaarheid opmerkingen.
        /// </summary>
        public static string Person_AvailabilityNote {
            get {
                return ResourceManager.GetString("Person_AvailabilityNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier alle extra informatie in m.b.t. beschikbaarheid..
        /// </summary>
        public static string Person_AvailabilityNote_Help {
            get {
                return ResourceManager.GetString("Person_AvailabilityNote_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact informatie.
        /// </summary>
        public static string Person_ContactInformation {
            get {
                return ResourceManager.GetString("Person_ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum.
        /// </summary>
        public static string Person_DateOfBirth {
            get {
                return ResourceManager.GetString("Person_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen geldige datum.
        /// </summary>
        public static string Person_DateOfBirth_Error {
            get {
                return ResourceManager.GetString("Person_DateOfBirth_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum van de persoon.
        /// </summary>
        public static string Person_DateOfBirth_Help {
            get {
                return ResourceManager.GetString("Person_DateOfBirth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadres.
        /// </summary>
        public static string Person_Email {
            get {
                return ResourceManager.GetString("Person_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer hier het emailadres in.
        /// </summary>
        public static string Person_Email_Help {
            get {
                return ResourceManager.GetString("Person_Email_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Person_Name {
            get {
                return ResourceManager.GetString("Person_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerkingen.
        /// </summary>
        public static string Person_Note {
            get {
                return ResourceManager.GetString("Person_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier alle niet geclassificeerde informatie in..
        /// </summary>
        public static string Person_Note_Help {
            get {
                return ResourceManager.GetString("Person_Note_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string Person_Phone {
            get {
                return ResourceManager.GetString("Person_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer, bijv. 0612345678.
        /// </summary>
        public static string Person_Phone_Help {
            get {
                return ResourceManager.GetString("Person_Phone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opgepakt.
        /// </summary>
        public static string PickedUp {
            get {
                return ResourceManager.GetString("PickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppakken.
        /// </summary>
        public static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats reactie.
        /// </summary>
        public static string PlaceComment {
            get {
                return ResourceManager.GetString("PlaceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens wijzigen.
        /// </summary>
        public static string Profile_Edit {
            get {
                return ResourceManager.GetString("Profile_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit project is gesloten, er kunnen geen taken meer aangemaakt worden..
        /// </summary>
        public static string Project_Closed {
            get {
                return ResourceManager.GetString("Project_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectdetails.
        /// </summary>
        public static string Project_Details {
            get {
                return ResourceManager.GetString("Project_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectinformatie.
        /// </summary>
        public static string Project_Information {
            get {
                return ResourceManager.GetString("Project_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze naam is al in gebruik, kies een andere.
        /// </summary>
        public static string Project_Name_AlreadyExists {
            get {
                return ResourceManager.GetString("Project_Name_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer een naam in.
        /// </summary>
        public static string Project_Name_Required {
            get {
                return ResourceManager.GetString("Project_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecten.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat gesloten projecten zien.
        /// </summary>
        public static string Projects_ShowClosed {
            get {
                return ResourceManager.GetString("Projects_ShowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord aanvragen.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaterdag.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan en nieuw.
        /// </summary>
        public static string SaveAndNew {
            get {
                return ResourceManager.GetString("SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek een klant.
        /// </summary>
        public static string Search_Customer {
            get {
                return ResourceManager.GetString("Search_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afmelden.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingelogd als.
        /// </summary>
        public static string SignedInAs {
            get {
                return ResourceManager.GetString("SignedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login met GitHub.
        /// </summary>
        public static string SignIn_GitHub {
            get {
                return ResourceManager.GetString("SignIn_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sinds.
        /// </summary>
        public static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorteren.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zondag.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ondersteuning geregeld.
        /// </summary>
        public static string SupportIsArranged {
            get {
                return ResourceManager.GetString("SupportIsArranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takenlijst.
        /// </summary>
        public static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle taken.
        /// </summary>
        public static string Tasks_All {
            get {
                return ResourceManager.GetString("Tasks_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltooide taken.
        /// </summary>
        public static string Tasks_Completed {
            get {
                return ResourceManager.GetString("Tasks_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open taken.
        /// </summary>
        public static string Tasks_Open {
            get {
                return ResourceManager.GetString("Tasks_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voortgang taken.
        /// </summary>
        public static string Tasks_Progress {
            get {
                return ResourceManager.GetString("Tasks_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak.
        /// </summary>
        public static string TheIssue {
            get {
                return ResourceManager.GetString("TheIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donderdag.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijdlijn.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aan.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dinsdag.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeboekt.
        /// </summary>
        public static string Unbooked {
            get {
                return ResourceManager.GetString("Unbooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload afbeelding/bestand.
        /// </summary>
        public static string Upload_picture_file {
            get {
                return ResourceManager.GetString("Upload_picture_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum geupload.
        /// </summary>
        public static string UploadDate {
            get {
                return ResourceManager.GetString("UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader.
        /// </summary>
        public static string Uploader {
            get {
                return ResourceManager.GetString("Uploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoed.
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoed tickets.
        /// </summary>
        public static string Urgent_Issues {
            get {
                return ResourceManager.GetString("Urgent_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijwilliger.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woensdag.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaar.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een jaar.
        /// </summary>
        public static string Year_Help {
            get {
                return ResourceManager.GetString("Year_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
